# Generated by Django 2.0.6 on 2018-06-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsSettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TruckTypes',
        ),
        migrations.AddField(
            model_name='dimensions',
            name='trucktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucknames', to='logisticsSettings.Truck'),
        ),
    ]
