# Generated by Django 2.0.6 on 2018-06-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsSettings', '0002_auto_20180622_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('trucktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='logisticsSettings.Truck')),
            ],
        ),
        migrations.RemoveField(
            model_name='dimensions',
            name='trucktype',
        ),
        migrations.DeleteModel(
            name='Dimensions',
        ),
    ]
